component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/org/.*
- ./bin/org/jgraph/.*
- ./bin/org/jgraph/pad/.*
- ./bin/org/jgraph/pad/actionsbase/.*
- ./bin/org/jgraph/pad/actionsbase/eager/.*
- ./bin/org/jgraph/pad/actionsbase/lazy/.*
- ./bin/org/jgraph/pad/graphcellsbase/.*
- ./bin/org/jgraph/pad/jgraphpad/.*
- ./bin/org/jgraph/pad/jgraphpad/util/.*
- ./bin/org/jgraph/pad/palettebase/.*
- ./bin/org/jgraph/pad/subjgraph/.*
- ./bin/org/jgraph/plugins/.*
- ./bin/org/jgraph/plugins/algebra/.*
- ./bin/org/jgraph/plugins/codecs/.*
- ./bin/org/jgraph/plugins/console/.*
- ./bin/org/jgraph/plugins/gpgraph/.*
- ./bin/org/jgraph/plugins/layouts/.*
- ./bin/org/jgraph/plugins/library/.*
- ./bin/org/jgraph/plugins/misc/.*
- ./bin/org/jgraph/plugins/translations/.*
- ./bin/org/microplatform/.*
- ./bin/org/microplatform/actions/.*
- ./bin/org/microplatform/gui/.*
- ./bin/org/microplatform/io/.*
- ./bin/org/microplatform/loaders/.*
- ./bin/org/microplatform/web/.*
- ./bin/org/microplatform/web/applet/.*
- ./bin/org/microplatform/web/webstart/.*
- ./lib/.*
- ./lib/ant/.*
- ./lib/apache/.*
- ./lib/java/.*
- ./lib/javascript/.*
- ./lib/lib/.*
- ./lib/lib/ant/.*
- ./lib/lib/apache/.*
- ./lib/lib/java/.*
- ./lib/lib/javascript/.*
- ./lib/lib/metainf/.*
- ./lib/lib/metainf/services/.*
- ./lib/lib/moinmoin/.*
- ./lib/metainf/.*
- ./lib/metainf/services/.*
- ./lib/moinmoin/.*
- ./packed/.*
- ./unpacked/.*
